2020-05-22 15:01:49,518:Survey Assist - v1.0:Started Application

2020-05-22 15:01:53,879:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 15:04:34,728:Survey Assist - v1.0:Started Application

2020-05-22 15:04:39,409:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 15:04:52,040:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

5
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2607, in change_station_height
    self.subsequent_station_setups[line_number].add(formatted_line['Point_ID'])
KeyError: 5
2020-05-22 15:07:35,580:Survey Assist - v1.0:Started Application

2020-05-22 15:07:39,159:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 15:07:54,311:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

descriptor 'get' for 'dict' objects doesn't apply to 'str' object
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2650, in change_station_height
    prev_averaged_coordinates = new_stn_coordinates.get(point_id) # retrieve previous average coordinates if they exist
TypeError: descriptor 'get' for 'dict' objects doesn't apply to 'str' object
2020-05-22 15:11:51,381:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

descriptor 'get' for 'dict' objects doesn't apply to 'str' object
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2650, in change_station_height
    prev_averaged_coordinates = new_stn_coordinates.get(point_id) # retrieve previous average coordinates if they exist
TypeError: descriptor 'get' for 'dict' objects doesn't apply to 'str' object
2020-05-22 15:15:39,686:Survey Assist - v1.0:Started Application

2020-05-22 15:15:44,206:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 15:16:30,552:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'STN04'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2659, in change_station_height
    new_stn_elevation = new_stn_coordinates[station][2]
KeyError: 'STN04'
2020-05-22 15:18:34,381:Survey Assist - v1.0:Started Application

2020-05-22 15:18:40,348:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 15:41:57,180:Survey Assist - v1.0:Started Application

2020-05-22 15:42:01,409:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:20:01,240:Survey Assist - v1.0:Started Application

2020-05-22 16:20:06,128:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:21:05,489:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'STN04'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2660, in change_station_height
    stn_coordinates = self.new_stn_coordinates[station]
KeyError: 'STN04'
2020-05-22 16:25:37,819:Survey Assist - v1.0:Started Application

2020-05-22 16:25:43,455:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:27:19,875:Survey Assist - v1.0:Started Application

2020-05-22 16:27:25,659:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:29:13,391:Survey Assist - v1.0:Started Application

2020-05-22 16:29:18,207:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:29:25,135:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2663, in change_station_height
    gsi.update_station_elevation(line_number, new_stn_elevation)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\GSI.py", line 134, in update_station_elevation
    org_field_value = match.group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-05-22 16:30:04,125:Survey Assist - v1.0:Started Application

2020-05-22 16:30:08,018:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:32:31,578:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'STN04'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2660, in change_station_height
    stn_coordinates = self.new_stn_coordinates[station]
KeyError: 'STN04'
2020-05-22 16:34:29,411:Survey Assist - v1.0:Started Application

2020-05-22 16:34:37,393:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:35:10,412:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'STN04'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2660, in change_station_height
    stn_coordinates = self.new_stn_coordinates[station]
KeyError: 'STN04'
2020-05-22 16:57:07,381:Survey Assist - v1.0:Started Application

2020-05-22 16:57:12,550:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:57:37,049:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:58:18,067:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 16:59:37,226:Survey Assist - v1.0:Started Application

2020-05-22 16:59:41,893:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:02:46,475:Survey Assist - v1.0:Started Application

2020-05-22 17:02:51,003:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:06:58,269:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:10:24,191:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719.GSI
2020-05-22 17:12:34,657:Survey Assist - v1.0:Started Application

2020-05-22 17:12:41,785:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:12:49,053:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2664, in change_station_height
    gsi.update_station_elevation(line_number-1, new_stn_elevation)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\GSI.py", line 134, in update_station_elevation
    org_field_value = match.group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-05-22 17:14:25,197:Survey Assist - v1.0:Started Application

2020-05-22 17:14:29,284:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:16:18,005:Survey Assist - v1.0:Started Application

2020-05-22 17:16:38,748:Survey Assist - v1.0:Started Application

2020-05-22 17:16:43,612:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:17:31,976:Survey Assist - v1.0:Started Application

2020-05-22 17:17:35,222:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:23:53,631:Survey Assist - v1.0:Started Application

2020-05-22 17:23:58,628:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:25:51,706:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:27:18,332:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:31:20,827:Survey Assist - v1.0:Started Application

2020-05-22 17:31:24,956:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:31:32,513:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

could not convert string to float: 
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2681, in change_station_height
    float(point_stn_elevation)])
ValueError: could not convert string to float: 
2020-05-22 17:32:37,308:Survey Assist - v1.0:Started Application

2020-05-22 17:32:40,456:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:34:14,146:Survey Assist - v1.0:Started Application

2020-05-22 17:34:32,195:Survey Assist - v1.0:Started Application

2020-05-22 17:34:36,487:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:36:45,513:Survey Assist - v1.0:Started Application

2020-05-22 17:36:49,206:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:36:58,798:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

[<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2675, in change_station_height
    point_stn_elevation = str(decimalize_value(point_stn_elevation, self.precision))
  File "C:\Users\Richard\PycharmProjects\Survey Assist\utilities.py", line 28, in decimalize_value
    return Decimal(in_value).quantize(Decimal('1.000'))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
2020-05-22 17:37:59,343:Survey Assist - v1.0:Started Application

2020-05-22 17:38:02,971:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:38:09,095:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

could not convert string to float: 
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2675, in change_station_height
    point_stn_elevation = str(decimalize_value(float(point_stn_elevation), self.precision))
ValueError: could not convert string to float: 
2020-05-22 17:39:13,379:Survey Assist - v1.0:Started Application

2020-05-22 17:39:19,191:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:39:26,684:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

could not convert string to float: 
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2685, in change_station_height
    self.new_stn_coordinates[point_id] = [float(point_easting), float(point_northing), float(point_stn_elevation)]
ValueError: could not convert string to float: 
2020-05-22 17:40:14,739:Survey Assist - v1.0:Started Application

2020-05-22 17:40:18,737:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:41:52,389:Survey Assist - v1.0:Started Application

2020-05-22 17:41:56,205:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 17:43:47,207:Survey Assist - v1.0:Started Application

2020-05-22 17:43:53,034:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-22 21:35:17,423:Survey Assist - v1.0:Started Application

2020-05-22 21:35:25,566:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200518/TS/EDITING/ARTC_903_MON_V2_TS60_180520_EDITED.GSI
2020-05-23 11:01:46,640:Survey Assist - v1.0:Started Application

2020-05-23 11:02:19,222:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/ARTC_903_compnet 240220.GSI
2020-05-23 13:45:15,452:Survey Assist - v1.0:Started Application

2020-05-23 13:45:29,784:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-23 13:45:36,081:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 13:49:57,674:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/Raumer fix 150520_Sorted.gsi
2020-05-23 13:50:49,033:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-23 13:50:53,893:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 13:54:54,147:Survey Assist - v1.0:Started Application

2020-05-23 13:54:59,268:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/MR140519.GSI
2020-05-23 13:55:09,299:Survey Assist - v1.0:An unexpected error has occurred

fix_target_height()

could not convert string to float: 
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2512, in fix_target_height
    corrections = self.get_target_height_corrections(line_number, new_target_height)
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2549, in get_target_height_corrections
    old_elevation = float(formatted_line['Elevation'])
ValueError: could not convert string to float: 
2020-05-23 13:58:38,737:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/MR140519.GSI
2020-05-23 14:00:40,254:Survey Assist - v1.0:Started Application

2020-05-23 14:00:46,424:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/MR140519.GSI
2020-05-23 14:04:09,882:Survey Assist - v1.0:Started Application

2020-05-23 14:04:14,549:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/MR140519.GSI
2020-05-23 14:35:57,186:Survey Assist - v1.0:Started Application

2020-05-23 14:36:07,565:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:36:20,049:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/MR140519.GSI
2020-05-23 14:36:36,158:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:38:13,294:Survey Assist - v1.0:Started Application

2020-05-23 14:38:32,096:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:39:14,349:Survey Assist - v1.0:Started Application

2020-05-23 14:39:34,174:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:40:43,018:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:42:07,455:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:44:49,229:Survey Assist - v1.0:Started Application

2020-05-23 14:45:12,721:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:48:25,974:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

unsupported operand type(s) for -: 'str' and 'int'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2661, in change_station_height
    formatted_line = gsi.get_formatted_line(formatted_line_number)
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\GSI.py", line 436, in get_formatted_line
    return self.formatted_lines[line_number - 1]
TypeError: unsupported operand type(s) for -: 'str' and 'int'
2020-05-23 14:49:15,926:Survey Assist - v1.0:Started Application

2020-05-23 14:49:20,237:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:52:32,268:Survey Assist - v1.0:Started Application

2020-05-23 14:52:37,408:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 14:54:24,718:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2664, in change_station_height
    gsi.update_station_height(formatted_line_number, coordinate_list[2])
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\GSI.py", line 106, in update_station_height
    org_field_value = match.group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-05-23 15:05:05,914:Survey Assist - v1.0:Started Application

2020-05-23 15:05:11,471:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:05:17,857:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

get_list_of_station_setups() missing 1 required positional argument: 'formatted_lines'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2609, in change_station_height
    station_setup_dic = gsi.get_list_of_station_setups()
TypeError: get_list_of_station_setups() missing 1 required positional argument: 'formatted_lines'
2020-05-23 15:05:43,890:Survey Assist - v1.0:Started Application

2020-05-23 15:05:47,628:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:09:16,170:Survey Assist - v1.0:Started Application

2020-05-23 15:09:21,752:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:09:27,480:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

Unexpected error changing station height
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2667, in change_station_height
    raise Exception("Unexpected error changing station height")
Exception: Unexpected error changing station height
2020-05-23 15:09:49,162:Survey Assist - v1.0:Started Application

2020-05-23 15:09:58,596:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:11:37,017:Survey Assist - v1.0:Started Application

2020-05-23 15:11:42,533:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:11:47,650:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'float' object has no attribute 'replace'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2665, in change_station_height
    gsi.update_station_height(formatted_line_number, coordinate_list[2])
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\GSI.py", line 113, in update_station_height
    new_station_height = new_station_height.replace(".", "")
AttributeError: 'float' object has no attribute 'replace'
2020-05-23 15:13:02,916:Survey Assist - v1.0:Started Application

2020-05-23 15:13:06,690:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:13:51,737:Survey Assist - v1.0:Started Application

2020-05-23 15:13:57,268:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:14:03,861:Survey Assist - v1.0:An unexpected error has occurred

update_station_height()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2666, in change_station_height
    gsi.update_elevation(formatted_line_number, new_elevation)
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\GSI.py", line 300, in update_elevation
    old_elevation_unformatted = match.group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-05-23 15:15:01,461:Survey Assist - v1.0:Started Application

2020-05-23 15:15:05,518:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:16:01,315:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:31:59,681:Survey Assist - v1.0:Started Application

2020-05-23 15:32:03,768:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:33:26,281:Survey Assist - v1.0:Started Application

2020-05-23 15:33:30,221:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:34:52,508:Survey Assist - v1.0:Started Application

2020-05-23 15:34:57,705:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:43:12,033:Survey Assist - v1.0:Started Application

2020-05-23 15:43:16,550:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:43:24,240:Survey Assist - v1.0:An unexpected error has occurred

fix_target_height()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2521, in fix_target_height
    gsi.update_station_elevation(stn_line_number, new_elevation)
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\GSI.py", line 134, in update_station_elevation
    org_field_value = match.group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-05-23 15:45:53,812:Survey Assist - v1.0:Started Application

2020-05-23 15:45:57,580:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:46:34,034:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:47:20,346:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 15:53:55,661:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 16:07:44,255:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/Raumer fix 150520_Sorted.gsi
2020-05-23 16:11:03,817:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED_STNUpdated_TgtUpdated_Sorted.gsi
2020-05-23 16:12:26,661:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED_STNUpdated_TgtUpdated.gsi
2020-05-23 16:12:54,833:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 16:14:18,301:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 16:15:23,458:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 16:15:40,880:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED_STNUpdated_TgtUpdated_Sorted.gsi
2020-05-23 16:20:08,648:Survey Assist - v1.0:Started Application

2020-05-23 16:20:13,379:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED_STNUpdated_TgtUpdated_Sorted.gsi
2020-05-23 16:23:33,412:Survey Assist - v1.0:Started Application

2020-05-23 16:23:46,723:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 16:24:57,061:Survey Assist - v1.0:Started Application

2020-05-23 16:25:02,426:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
2020-05-23 16:25:50,285:Survey Assist - v1.0:Started Application

2020-05-23 16:25:54,224:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520_EDITED.GSI
