2020-06-18 09:11:51,366:Survey Assist - v1.0 :************************** STARTED APPLICATION - User: ??**************************
2020-06-18 09:12:00,694:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/2D Survey MR050819.GSI
2020-06-18 09:12:07,865:Survey Assist - v1.0 :************************** STARTED APPLICATION - User: ??**************************
2020-06-18 09:12:10,896:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/ARTC_903_TS15 230320.GSI
2020-06-18 09:12:45,859:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: ?? *************************
2020-06-18 09:12:50,415:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/3D STN named incorrect.GSI
2020-06-22 10:03:55,552:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: ?? *************************
2020-06-22 10:04:32,170:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/3D MR_120819_3D error change.gsi
2020-06-22 11:35:01,883:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:15:49,544:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:23:09,488:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:35:08,025:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:37:56,226:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:42:18,442:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:42:49,296:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200623/TS/EDITING/ARTC_903_MON_V2_TS15_230620_EDITED.GSI
2020-06-23 22:43:27,218:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200623/TS/EDITING/ARTC_903_MON_V2_MS60_230620_EDITED.GSI
2020-06-24 08:57:56,959:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 08:58:27,202:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.GSI
2020-06-24 09:04:15,607:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.GSI
2020-06-24 09:05:10,828:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:05:15,515:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.GSI
2020-06-24 09:07:09,030:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620 - Copy.GSI
2020-06-24 09:08:43,514:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.GSI
2020-06-24 09:15:11,838:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:16:20,633:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:16:27,795:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.gsi
2020-06-24 09:17:05,328:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:17:09,623:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.gsi
2020-06-24 09:22:07,699:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:22:35,296:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.gsi
2020-06-24 09:23:34,185:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.gsi
2020-06-24 09:29:51,457:Survey Assist - v1.0 :An unexpected error has occurred

update_fixed_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3315, in update_fixed_file
    coordinate_file = CoordinateFile.getCordinateFile(self.coordinate_file_path, coordinate_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 35, in getCordinateFile
    return ASCCoordinateFile(filepath)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 123, in __init__
    super().__init__(coordinate_file_path, 'ASC')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 29, in __init__
    self.format_coordinate_file()
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 134, in format_coordinate_file
    stripped_line_list = line_list[0:self.getIndexElevation(line) + 1]
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 147, in getIndexElevation
    northing_value = CoordinateFile.re_pattern_northing.search(line).group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:30:36,338:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:30:47,593:Survey Assist - v1.0 :An unexpected error has occurred

update_fixed_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3315, in update_fixed_file
    coordinate_file = CoordinateFile.getCordinateFile(self.coordinate_file_path, coordinate_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 35, in getCordinateFile
    return ASCCoordinateFile(filepath)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 123, in __init__
    super().__init__(coordinate_file_path, 'ASC')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 29, in __init__
    self.format_coordinate_file()
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 134, in format_coordinate_file
    stripped_line_list = line_list[0:self.getIndexElevation(line) + 1]
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 147, in getIndexElevation
    northing_value = CoordinateFile.re_pattern_northing.search(line).group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:31:53,430:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:32:02,753:Survey Assist - v1.0 :An unexpected error has occurred

update_fixed_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3315, in update_fixed_file
    coordinate_file = CoordinateFile.getCordinateFile(self.coordinate_file_path, coordinate_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 35, in getCordinateFile
    return ASCCoordinateFile(filepath)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 123, in __init__
    super().__init__(coordinate_file_path, 'ASC')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 29, in __init__
    self.format_coordinate_file()
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 134, in format_coordinate_file
    stripped_line_list = line_list[0:self.getIndexElevation(line) + 1]
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 147, in getIndexElevation
    northing_value = CoordinateFile.re_pattern_northing.search(line).group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:34:47,695:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:36:56,922:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 Menangle Road/200624/TS/EDITING/A7MR 240620_EDITED.GSI
2020-06-24 09:44:51,192:Survey Assist - v1.0 :An unexpected error has occurred

update_STD_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3428, in update_STD_file
    std_file = STDCoordinateFile(self.std_file_path)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 158, in __init__
    super().__init__(coordinate_file_path, 'STD')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 30, in __init__
    self.build_coordinate_dictionary(file_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 73, in build_coordinate_dictionary
    point_name = point_match.group().replace('"', '')
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:45:39,772:Survey Assist - v1.0 :An unexpected error has occurred

update_STD_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3428, in update_STD_file
    std_file = STDCoordinateFile(self.std_file_path)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 158, in __init__
    super().__init__(coordinate_file_path, 'STD')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 30, in __init__
    self.build_coordinate_dictionary(file_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 73, in build_coordinate_dictionary
    point_name = point_match.group().replace('"', '')
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 11:38:52,553:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:39:01,701:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 17:08:31,469:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 17:08:39,436:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 Menangle Road/200624/A7MR 240620_EDITED_TgtUpdated_PCUpdated_Sorted.gsi
2020-06-26 15:15:01,433:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:22:14,961:Survey Assist - v1.0 :Error has occurred creating Job Tracker object.

close() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 4425, in __init__
    self.job_tracker_bar = JobTrackerBar(self.main_window, self.menu_bar.user_config.user_initials)
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2080, in __init__
    self.job_tracker = JobTracker(self.job_tracker_filepath, logger)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\job_tracker.py", line 22, in __init__
    self.workbook.close(True)
TypeError: close() takes 1 positional argument but 2 were given
2020-06-26 15:26:25,674:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:27:11,502:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:27:31,701:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
