2020-06-18 09:11:51,366:Survey Assist - v1.0 :************************** STARTED APPLICATION - User: ??**************************
2020-06-18 09:12:00,694:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/2D Survey MR050819.GSI
2020-06-18 09:12:07,865:Survey Assist - v1.0 :************************** STARTED APPLICATION - User: ??**************************
2020-06-18 09:12:10,896:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/ARTC_903_TS15 230320.GSI
2020-06-18 09:12:45,859:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: ?? *************************
2020-06-18 09:12:50,415:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/3D STN named incorrect.GSI
2020-06-22 11:22:34,480:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 09:43:53,374:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 12:45:00,723:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 12:45:19,997:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/2D Survey MR050819.GSI
2020-06-23 12:46:56,442:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:52:59,081:Survey Assist - v1.0 :Job Tracker excel spreadsheet not found

[Errno 2] No such file or directory: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\job_tracker.py", line 19, in __init__
    self.workbook = load_workbook(self.job_tracker_filepath, read_only=True)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openpyxl\reader\excel.py", line 312, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1250, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-06-24 09:53:05,680:Survey Assist - v1.0 :Error has occurred creating Job Tracker object.

No Job Names Found
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 4400, in __init__
    self.job_tracker_bar = JobTrackerBar(self.main_window, self.menu_bar.user_config.user_initials)
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2109, in __init__
    self.jt_job_name_combo['values'] = self.get_combobox_values()
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2195, in get_combobox_values
    raise Exception("No Job Names Found")
Exception: No Job Names Found
2020-06-24 09:53:42,733:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:02:40,195:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:04:26,210:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-06-24 10:08:28,111:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:08:32,665:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-06-24 10:14:21,879:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:14:41,985:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:14:59,948:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:17:03,856:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:17:52,896:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:22:43,469:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:23:26,900:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:25:30,306:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:25:55,638:Survey Assist - v1.0 :Job Tracker excel spreadsheet currently in use

[Errno 13] Permission denied: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2325, in save_job_to_excel
    workbook.save(filename=self.job_tracker_filepath)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1250, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-06-24 10:26:02,527:Survey Assist - v1.0 :Error has occurred in JobTracker init().

wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2339, in save_job_to_excel
    self.cb_callback(None)
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2175, in cb_callback
    self.jt_user_entry.insert(0, survey_job.initials)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 3051, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
2020-06-24 10:28:06,126:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:28:30,856:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:29:38,103:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:29:49,871:Survey Assist - v1.0 :Error has occurred in JobTracker init().

wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2339, in save_job_to_excel
    self.cb_callback(None)
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2175, in cb_callback
    self.jt_user_entry.insert(0, survey_job.initials)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 3051, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
2020-06-24 10:31:11,401:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:32:47,986:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:40:41,555:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:41:33,792:Survey Assist - v1.0 :Error has occurred in JobTracker init().

wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2339, in save_job_to_excel
    self.cb_callback(None)
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2175, in cb_callback
    self.jt_user_entry.insert(0, survey_job.initials)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 3051, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
2020-06-24 10:42:45,843:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:42:59,876:Survey Assist - v1.0 :Error has occurred in JobTracker init().

wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2339, in save_job_to_excel
    self.cb_callback(None)
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2175, in cb_callback
    self.jt_user_entry.insert(0, survey_job.initials)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 3051, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
2020-06-24 10:43:28,105:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:43:49,432:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:44:33,313:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:44:42,303:Survey Assist - v1.0 :Error has occurred in JobTracker init().

wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2339, in save_job_to_excel
    self.cb_callback(None)
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2175, in cb_callback
    self.jt_user_entry.insert(0, survey_job.initials)
  File "C:\Users\rjwal_000\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 3051, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".!mainwindow.!frame2.!entry insert index text"
2020-06-24 10:45:50,831:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:48:14,370:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:48:52,008:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:52:28,786:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:52:57,560:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:54:31,164:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:55:07,536:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 10:56:07,414:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-06-24 11:00:13,042:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:00:45,114:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:01:14,846:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:01:40,717:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:04:09,705:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:04:47,859:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:11:59,329:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:12:39,104:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:13:47,183:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:16:11,642:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:17:25,148:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:18:41,982:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:19:01,718:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:25:13,030:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:25:36,802:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:26:24,476:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200529/TS/EDITING/ARTC_903_MON_V2_TS60_240620_EDITED.GSI
