2020-06-18 09:11:51,366:Survey Assist - v1.0 :************************** STARTED APPLICATION - User: ??**************************
2020-06-18 09:12:00,694:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/2D Survey MR050819.GSI
2020-06-18 09:12:07,865:Survey Assist - v1.0 :************************** STARTED APPLICATION - User: ??**************************
2020-06-18 09:12:10,896:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/ARTC_903_TS15 230320.GSI
2020-06-18 09:12:45,859:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: ?? *************************
2020-06-18 09:12:50,415:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/3D STN named incorrect.GSI
2020-06-22 10:03:55,552:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: ?? *************************
2020-06-22 10:04:32,170:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/3D MR_120819_3D error change.gsi
2020-06-22 11:35:01,883:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:15:49,544:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:23:09,488:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:35:08,025:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:37:56,226:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:42:18,442:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-23 22:42:49,296:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200623/TS/EDITING/ARTC_903_MON_V2_TS15_230620_EDITED.GSI
2020-06-23 22:43:27,218:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200623/TS/EDITING/ARTC_903_MON_V2_MS60_230620_EDITED.GSI
2020-06-24 08:57:56,959:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 08:58:27,202:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.GSI
2020-06-24 09:04:15,607:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.GSI
2020-06-24 09:05:10,828:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:05:15,515:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.GSI
2020-06-24 09:07:09,030:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620 - Copy.GSI
2020-06-24 09:08:43,514:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.GSI
2020-06-24 09:15:11,838:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:16:20,633:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:16:27,795:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.gsi
2020-06-24 09:17:05,328:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:17:09,623:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/Downloads/A7MR 240620.gsi
2020-06-24 09:22:07,699:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:22:35,296:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.gsi
2020-06-24 09:23:34,185:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.gsi
2020-06-24 09:29:51,457:Survey Assist - v1.0 :An unexpected error has occurred

update_fixed_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3315, in update_fixed_file
    coordinate_file = CoordinateFile.getCordinateFile(self.coordinate_file_path, coordinate_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 35, in getCordinateFile
    return ASCCoordinateFile(filepath)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 123, in __init__
    super().__init__(coordinate_file_path, 'ASC')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 29, in __init__
    self.format_coordinate_file()
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 134, in format_coordinate_file
    stripped_line_list = line_list[0:self.getIndexElevation(line) + 1]
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 147, in getIndexElevation
    northing_value = CoordinateFile.re_pattern_northing.search(line).group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:30:36,338:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:30:47,593:Survey Assist - v1.0 :An unexpected error has occurred

update_fixed_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3315, in update_fixed_file
    coordinate_file = CoordinateFile.getCordinateFile(self.coordinate_file_path, coordinate_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 35, in getCordinateFile
    return ASCCoordinateFile(filepath)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 123, in __init__
    super().__init__(coordinate_file_path, 'ASC')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 29, in __init__
    self.format_coordinate_file()
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 134, in format_coordinate_file
    stripped_line_list = line_list[0:self.getIndexElevation(line) + 1]
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 147, in getIndexElevation
    northing_value = CoordinateFile.re_pattern_northing.search(line).group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:31:53,430:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:32:02,753:Survey Assist - v1.0 :An unexpected error has occurred

update_fixed_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3315, in update_fixed_file
    coordinate_file = CoordinateFile.getCordinateFile(self.coordinate_file_path, coordinate_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 35, in getCordinateFile
    return ASCCoordinateFile(filepath)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 123, in __init__
    super().__init__(coordinate_file_path, 'ASC')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 29, in __init__
    self.format_coordinate_file()
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 134, in format_coordinate_file
    stripped_line_list = line_list[0:self.getIndexElevation(line) + 1]
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 147, in getIndexElevation
    northing_value = CoordinateFile.re_pattern_northing.search(line).group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:34:47,695:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 09:36:56,922:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 Menangle Road/200624/TS/EDITING/A7MR 240620_EDITED.GSI
2020-06-24 09:44:51,192:Survey Assist - v1.0 :An unexpected error has occurred

update_STD_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3428, in update_STD_file
    std_file = STDCoordinateFile(self.std_file_path)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 158, in __init__
    super().__init__(coordinate_file_path, 'STD')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 30, in __init__
    self.build_coordinate_dictionary(file_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 73, in build_coordinate_dictionary
    point_name = point_match.group().replace('"', '')
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 09:45:39,772:Survey Assist - v1.0 :An unexpected error has occurred

update_STD_file()

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 3428, in update_STD_file
    std_file = STDCoordinateFile(self.std_file_path)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 158, in __init__
    super().__init__(coordinate_file_path, 'STD')
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 30, in __init__
    self.build_coordinate_dictionary(file_type)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\compnet.py", line 73, in build_coordinate_dictionary
    point_name = point_match.group().replace('"', '')
AttributeError: 'NoneType' object has no attribute 'group'
2020-06-24 11:38:52,553:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 11:39:01,701:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 17:08:31,469:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-24 17:08:39,436:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 Menangle Road/200624/A7MR 240620_EDITED_TgtUpdated_PCUpdated_Sorted.gsi
2020-06-26 15:15:01,433:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:22:14,961:Survey Assist - v1.0 :Error has occurred creating Job Tracker object.

close() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 4425, in __init__
    self.job_tracker_bar = JobTrackerBar(self.main_window, self.menu_bar.user_config.user_initials)
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2080, in __init__
    self.job_tracker = JobTracker(self.job_tracker_filepath, logger)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\job_tracker.py", line 22, in __init__
    self.workbook.close(True)
TypeError: close() takes 1 positional argument but 2 were given
2020-06-26 15:26:25,674:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:27:11,502:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:27:31,701:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:34:55,070:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:41:01,967:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:45:36,932:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 15:47:16,133:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:02:30,869:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:04:47,355:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:07:39,206:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:07:44,164:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:10:15,859:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:11:13,283:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:13:39,067:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:14:33,189:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:26:12,347:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:41:32,437:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:41:48,288:Survey Assist - v1.0 :Error has occurred in JobTracker init().

name 'current_job_selected_line' is not defined
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2345, in save_job_to_excel
    excel_row_to_update = str(10 + current_job_selected_line)
NameError: name 'current_job_selected_line' is not defined
2020-06-26 16:42:28,925:Survey Assist - v1.0 :Error has occurred in JobTracker init().

name 'current_job_selected_line' is not defined
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2345, in save_job_to_excel
    excel_row_to_update = str(10 + current_job_selected_line)
NameError: name 'current_job_selected_line' is not defined
2020-06-26 16:42:41,660:Survey Assist - v1.0 :Error has occurred in JobTracker init().

name 'current_job_selected_line' is not defined
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2345, in save_job_to_excel
    excel_row_to_update = str(10 + current_job_selected_line)
NameError: name 'current_job_selected_line' is not defined
2020-06-26 16:44:09,564:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:44:22,041:Survey Assist - v1.0 :Error has occurred in JobTracker init().

name 'current_job_selected_line' is not defined
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2345, in save_job_to_excel
    excel_row_to_update = str(10 + current_job_selected_line)
NameError: name 'current_job_selected_line' is not defined
2020-06-26 16:45:13,302:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:49:10,690:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:51:16,176:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:53:27,193:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 16:53:34,026:Survey Assist - v1.0 :Error has occurred in JobTracker init().

'Worksheet' object has no attribute 'iter_rowa'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2335, in save_job_to_excel
    for row in actions_sheet.iter_rowa(min_row=11, max_row=100, min_col=1, max_col=2):
AttributeError: 'Worksheet' object has no attribute 'iter_rowa'
2020-06-26 16:53:58,052:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 17:29:36,335:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 20:57:47,016:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:01:10,432:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:02:29,539:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:03:52,007:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:05:40,403:Survey Assist - v1.0 :Error has occurred in JobTracker init().

'datetime.datetime' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2338, in save_job_to_excel
    if job_name == row[0].value.strip() and job_date == row[1].value.strip():
AttributeError: 'datetime.datetime' object has no attribute 'strip'
2020-06-26 21:07:12,984:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:07:24,327:Survey Assist - v1.0 :Error has occurred in JobTracker init().

can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2351, in save_job_to_excel
    self.update_job_date(actions_sheet["B" + excel_row_to_update], self.jt_date_btn['text'])
TypeError: can only concatenate str (not "int") to str
2020-06-26 21:09:33,925:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:09:42,566:Survey Assist - v1.0 :Error has occurred in JobTracker init().

can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 2351, in save_job_to_excel
    self.update_job_date(actions_sheet["B" + excel_row_to_update], self.jt_date_btn['text'])
TypeError: can only concatenate str (not "int") to str
2020-06-26 21:14:11,220:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:16:16,113:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-26 21:16:27,801:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:11:09,882:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:11:42,894:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.gsi
2020-06-28 09:11:42,957:Survey Assist - v1.0 :An unexpected error has occurred

Problem opening up the GSI file

[Errno 2] No such file or directory: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Monitoring Files\\STN01.csv'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 556, in monitoring_create
    with open(out_csv, 'w', newline='') as my_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Monitoring Files\\STN01.csv'
2020-06-28 09:24:28,059:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:24:37,749:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A7MR 240620.gsi
2020-06-28 09:31:03,213:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:31:05,444:Survey Assist - v1.0 :Job Tracker excel spreadsheet not found

[Errno 2] No such file or directory: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:\Users\Richard\PycharmProjects\Survey Assist\job_tracker.py", line 20, in __init__
    with open(self.job_tracker_filepath, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-06-28 09:32:38,724:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:32:40,860:Survey Assist - v1.0 :Job Tracker excel spreadsheet not found

[Errno 2] No such file or directory: 'C:\\Users\\Richard Walter\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:\Users\Richard\PycharmProjects\Survey Assist\job_tracker.py", line 20, in __init__
    with open(self.job_tracker_filepath, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Richard Walter\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-06-28 09:33:39,508:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:36:07,756:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:55:48,335:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-28 09:59:51,444:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-29 16:29:14,878:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-06-29 16:31:49,844:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-02 13:04:52,580:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-09 08:04:59,450:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 17:18:08,323:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 17:19:00,348:Survey Assist - v1.0 :Error has occurred in JobTracker save_job_to_excel().

'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2337, in save_job_to_excel
    row_job_name = row[0].value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2020-07-14 17:19:17,481:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:39:37,569:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:42:49,479:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:43:04,878:Survey Assist - v1.0 :Error has occurred in JobTracker save_job_to_excel().

'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2337, in save_job_to_excel
    row_job_name = row[0].value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2020-07-14 21:43:12,301:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:43:20,780:Survey Assist - v1.0 :Error has occurred in JobTracker save_job_to_excel().

'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2337, in save_job_to_excel
    row_job_name = row[0].value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2020-07-14 21:44:16,723:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:50:45,989:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:50:57,768:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:55:54,483:Survey Assist - v1.0 :Job Tracker excel spreadsheet currently in use

[Errno 13] Permission denied: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 2368, in save_job_to_excel
    workbook.save(filename=self.job_tracker_filepath)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\rjwal_000\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-07-14 21:58:13,448:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 21:59:51,607:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 22:00:29,822:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 22:08:22,856:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 22:09:38,734:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 22:10:21,966:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 22:10:50,894:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 22:13:03,301:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-14 22:13:06,927:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-15 22:02:47,174:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-15 22:07:41,527:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-15 22:07:51,908:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-15 22:30:13,277:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-15 22:32:43,251:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-15 22:32:54,627:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-15 22:33:48,003:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-15 22:33:57,909:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 08:18:53,941:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 08:18:59,253:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 08:19:08,908:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 08:19:12,363:Survey Assist - v1.0 :Unknown error occurred in Print GSI

'MenuBar' object has no attribute 'job_tracker_filepath'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 504, in print_gsi
    workbook.save(filename=self.job_tracker_filepath)
AttributeError: 'MenuBar' object has no attribute 'job_tracker_filepath'
2020-07-16 08:19:42,447:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 08:19:50,794:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 08:28:52,464:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 08:28:55,075:Survey Assist - v1.0 :Print GSI excel spreadsheet is currently open

[Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 504, in print_gsi
    workbook.save(filename=print_gsi_excel_filepath)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
2020-07-16 08:33:07,963:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 08:33:13,978:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 08:33:22,206:Survey Assist - v1.0 :Print GSI excel spreadsheet is currently open

[Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 504, in print_gsi
    workbook.save(filename=print_gsi_excel_filepath)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
2020-07-16 16:36:48,472:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 16:37:02,145:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 16:37:10,212:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 16:40:22,116:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 16:49:00,620:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 16:49:05,774:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 16:49:08,963:Survey Assist - v1.0 :Print GSI excel spreadsheet is currently open

[Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 507, in print_gsi
    workbook.save(filename=print_gsi_excel_filepath)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
2020-07-16 16:51:10,683:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 16:51:14,947:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 16:59:11,603:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 16:59:23,525:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 17:03:42,089:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 17:03:46,431:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 17:05:34,618:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 17:05:38,681:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 17:08:08,889:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 17:08:14,416:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 17:14:50,901:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 17:14:56,165:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 22:34:01,548:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 22:34:31,543:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 22:37:35,650:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200529/TS/EDITING/ARTC_903_MON_V2_TS60_240620_EDITED.GSI
2020-07-16 22:38:21,771:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 22:38:25,853:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200529/TS/EDITING/ARTC_903_MON_V2_TS60_240620_EDITED.GSI
2020-07-16 22:38:30,213:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 22:49:31,848:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 22:49:37,134:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 22:49:39,384:Survey Assist - v1.0 :Print GSI excel spreadsheet is currently open

[Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 556, in print_gsi
    workbook.save(filename=print_gsi_excel_filepath)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'C:\\SurveyAssist\\Print GSI.xlsx'
2020-07-16 22:59:16,957:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 22:59:21,150:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 23:00:18,486:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 23:00:23,618:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-16 23:03:00,001:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 23:03:04,244:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200529/TS/EDITING/ARTC_903_MON_V2_TS60_240620_EDITED.GSI
2020-07-16 23:05:10,260:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-07-16 23:08:41,038:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-16 23:08:46,009:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 07:44:07,102:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 07:44:11,840:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-07-17 07:47:08,270:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 07:47:13,885:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-07-17 07:47:40,930:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 07:47:46,744:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 07:55:55,030:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 07:56:00,416:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 07:56:58,467:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 07:57:03,213:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 07:57:47,181:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 07:57:53,776:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 08:03:09,690:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 08:03:16,369:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 08:05:01,063:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 08:05:05,744:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 08:08:05,322:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 08:08:09,385:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 08:10:42,197:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-07-17 08:12:02,545:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 08:12:06,821:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 08:13:38,322:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-07-17 08:13:50,228:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 08:29:18,763:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 08:29:27,275:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 08:30:28,853:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/DA3B Swamps/200529/TS/EDITING/WC12 290520_EDITED.GSI
2020-07-17 08:30:51,009:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 08:31:20,702:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 08:31:27,838:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 09:10:31,903:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 09:10:43,716:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 09:15:02,002:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 09:15:05,853:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 09:16:21,931:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200529/TS/EDITING/ARTC_903_MON_V2_TS60_240620_EDITED.GSI
2020-07-17 09:19:19,504:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 09:19:23,775:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 09:21:15,494:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-07-17 09:23:32,260:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/DA3B Swamps/200529/TS/EDITING/WC12 290520_EDITED.GSI
2020-07-17 09:24:03,125:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 09:24:08,275:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-17 09:24:20,041:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200529/TS/EDITING/ARTC_903_MON_V2_TS60_240620_EDITED.GSI
2020-07-17 09:24:29,603:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/DA3B Swamps/200529/TS/EDITING/WC12 290520_EDITED.GSI
2020-07-17 09:25:20,275:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-17 09:25:25,853:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/DA3B Swamps/200529/TS/EDITING/WC12 290520_EDITED.GSI
2020-07-26 22:10:12,184:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-26 22:10:31,578:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/DA3B Swamps/200529/TS/EDITING/WC12 290520_EDITED.GSI
2020-07-26 22:10:38,609:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/SD/TS60/Gsi/A9MR210120.GSI
2020-07-29 17:17:37,151:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-29 17:31:53,960:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/HCCL_300620_Sorted.gsi
2020-07-29 17:34:55,006:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-07-29 17:35:00,459:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/HCCL_300620_Sorted.gsi
2020-07-29 17:36:33,741:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-08-08 08:52:13,172:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-09 15:40:55,897:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-09 15:41:08,703:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-08-13 08:49:04,781:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-13 08:49:15,953:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200529/TS/EDITING/ARTC_903_MON_V2_TS60_240620_EDITED.GSI
2020-08-13 08:50:06,600:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:27:41,604:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:28:39,854:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:29:26,611:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:33:44,476:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-08-24 15:40:25,340:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:41:23,066:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:42:50,482:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:43:32,621:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:44:23,693:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:44:38,967:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:45:43,057:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:46:04,983:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:46:45,443:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:47:04,058:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:52:22,783:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
2020-08-24 15:55:27,554:Survey Assist - v1.0 :OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719_EDITED.gsi
2020-08-24 15:56:48,631:Survey Assist - v1.0 :************************* STARTED APPLICATION - User: RW *************************
